create table person
(
    id            integer generated by default as identity
        primary key,
    full_name     varchar(100)
        unique,
    year_of_birth integer,
    login         varchar(30),
    password      varchar,
    role          varchar
);

alter table person
    owner to postgres;

create unique index person_login_uindex
    on person (login);

create table book
(
    id         integer generated by default as identity
        primary key,
    title      varchar(100) not null,
    author     varchar(100) not null,
    year       integer      not null,
    person_id  integer
                            references person
                                on delete set null,
    taken_time timestamp
);

alter table book
    owner to postgres;


